'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>typeof v==='number'?v.toFixed(3):'—';
const labels={pending:'未标注',correct:'正确',false_positive:'误判',uncertain:'无法判断'};
let data,current,filtered=[],drafts={},saving=false;
function icons(){window.lucide?.createIcons();}
function error(message){$('error').hidden=!message;$('error').textContent=message||'';}
function annotation(rid){return drafts[rid]||data.annotations[rid];}
function complete(c){return c.record_ids.every(id=>annotation(id).manual_verdict!=='pending');}
function updateProgress(){const count=Object.keys(data.records).filter(id=>annotation(id).manual_verdict!=='pending').length;$('progress').textContent=`已标注 ${count} / ${Object.keys(data.records).length}`;$('saveState').textContent=Object.keys(drafts).length?`${Object.keys(drafts).length} 项未保存`:'已保存';$('save').disabled=saving||!Object.keys(drafts).length;}
function queue(){filtered=data.cases.filter(c=>(!$('student').value||c.student_id===$('student').value)&&(!$('move').value||String(c.move_id)===$('move').value)&&(!$('pending').checked||!complete(c)));$('queue').innerHTML=filtered.map(c=>`<button class="case ${c.case_id===current?.case_id?'active':''}" data-case="${esc(c.case_id)}"><span>${esc(c.student_id)} · ${esc(c.move_name)}</span><small>${c.record_ids.filter(id=>annotation(id).manual_verdict!=='pending').length}/${c.record_ids.length}</small></button>`).join('');}
function review(rid){const a=annotation(rid);return `<div class="review" data-record="${esc(rid)}"><div class="verdicts" role="radiogroup" aria-label="${esc(rid)} 复核结论">${Object.entries(labels).map(([v,label])=>`<label class="verdict"><input type="radio" name="${esc(rid)}" value="${v}" ${a.manual_verdict===v?'checked':''}>${label}</label>`).join('')}</div><textarea aria-label="${esc(rid)} 备注" placeholder="备注" maxlength="4000">${esc(a.notes)}</textarea><div class="saved-meta">${esc(a.reviewer)} ${a.updated_at?esc(new Date(a.updated_at).toLocaleString()):''}</div></div>`;}
function rid(source,scope,id){return `${current.case_id}:${source}:${scope}:${id}`;}
function metricTable(ids){const metrics=current.metrics.filter(m=>!ids||ids.includes(m.metric_id));return `<div class="table-scroll"><table><thead><tr><th>指标</th><th>学生值 / 中心帧</th><th>教师 median ± 2MAD</th><th>教师 P10–P90</th></tr></thead><tbody>${metrics.map(m=>`<tr><td>${esc(m.label_zh)}<br>${esc(m.unit)}</td><td>${fmt(m.student.value)} / ${fmt(m.student.center_value)}</td><td>${fmt(m.teacher.median_2mad.lower)} – ${fmt(m.teacher.median_2mad.upper)}</td><td>${fmt(m.teacher.p10_p90.lower)} – ${fmt(m.teacher.p10_p90.upper)}</td></tr>`).join('')}</tbody></table></div>`;}
function finding(f){return `<article class="finding"><span class="badge ${f.assessment==='insufficient_evidence'?'warn':''}">${esc(f.finding_id)} · ${f.assessment==='insufficient_evidence'?'证据不足':'可能的问题'}</span><h3>${esc(f.problem)}</h3><div class="caption">判断依据</div><p>${esc(f.explanation)}</p><div class="caption">不确定性</div><p>${esc(f.uncertainty)}</p><div class="caption">训练指导</div><p class="guidance">${esc(f.guidance||'暂无纠正建议')}</p><details><summary>证据指标 · ${esc((f.evidence_metric_ids||[]).map(id=>current.metrics.find(m=>m.metric_id===id)?.label_zh||id).join(' / '))}</summary>${metricTable(f.evidence_metric_ids||[])}</details>${review(rid('F','finding',f.finding_id))}</article>`;}
function baseline(r){const id=rid('rule_baseline','metric',r.record_id);return `<article class="finding"><span class="badge ${r.decision==='needs_review'?'warn':''}">${esc(r.decision_zh)}</span><h3>${esc(r.metric_label_zh)}</h3><p>${esc(r.technique_aspect)}</p>${r.feedback?`<div class="caption">训练反馈</div><p class="guidance">${esc(r.feedback)}</p>`:''}${r.review_reasons_zh.length?`<div class="caption">复核原因</div><p>${esc(r.review_reasons_zh.join('；'))}</p>`:''}<details><summary>指标与参考范围</summary>${metricTable([r.metric_id])}</details>${data.records[id]?review(id):''}</article>`;}
function render(){queue();if(!current){$('content').innerHTML='<p class="empty">没有符合筛选条件的案例。</p>';updateProgress();return;}
const c=current;const i=filtered.findIndex(x=>x.case_id===c.case_id);const primary=c.baseline.filter(r=>r.decision==='feedback_candidate'||r.decision==='needs_review');const rest=c.baseline.filter(r=>!primary.includes(r));
$('content').innerHTML=`<div class="title"><div><small>${esc(c.case_id)} · 结束定势</small><h1>学生 ${esc(c.student_id)} · ${esc(c.move_name)}</h1></div><div class="navbuttons"><button id="prev" aria-label="上一案例" title="上一案例" ${i<=0?'disabled':''}><i data-lucide="chevron-left"></i></button><button id="next" aria-label="下一案例" title="下一案例" ${i>=filtered.length-1?'disabled':''}><i data-lucide="chevron-right"></i></button></div></div><p class="technique">${esc(c.technique)}</p><section class="images">${[['reference','参考锚点 · BV1WE411W7JB',c.reference_time],['student','学生 '+c.student_id,c.student_time]].map(([role,label,t])=>`<figure><figcaption>${esc(label)}<span>${fmt(t)} s</span></figcaption><button class="image-button" data-image="${esc(c.images[role])}" title="查看完整定势帧" aria-label="${esc(label)}大图"><img src="${esc(c.images[role])}" alt="${esc(label)}结束定势"></button></figure>`).join('')}</section><section class="columns"><div class="method f"><h2>Qwen · F 组 <small>${c.response.findings.length} 条 findings</small></h2><section class="summary"><h3>教练式总结 · coach_summary</h3><p>${esc(c.response.coach_summary)}</p>${review(rid('F','coach_summary','summary'))}</section>${c.response.findings.map(finding).join('')||'<p class="empty">未返回 findings</p>'}<details><summary>完整返回 JSON</summary><pre>${esc(JSON.stringify(c.response,null,2))}</pre></details></div><div class="method rule"><h2>Rule baseline <small>${primary.filter(r=>r.decision==='feedback_candidate').length} 条候选建议</small></h2><section class="summary"><h3>简短训练提示</h3><p>${esc(c.baseline_summary)}</p>${review(rid('rule_baseline','coach_summary','summary'))}</section>${primary.map(baseline).join('')}<details><summary>其他指标 · ${rest.length} 项</summary>${rest.map(baseline).join('')}</details></div></section>`;
icons();updateProgress();}
function changeReview(element){const holder=element.closest('[data-record]');if(!holder)return;const id=holder.dataset.record;drafts[id]={...annotation(id),manual_verdict:holder.querySelector('input:checked').value,notes:holder.querySelector('textarea').value,reviewer:$('reviewer').value};updateProgress();queue();}
async function save(){if(saving)return false;if(!Object.keys(drafts).length)return true;saving=true;const snapshot=JSON.parse(JSON.stringify(drafts));updateProgress();$('saveState').textContent='保存中…';try{const response=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':data.token},body:JSON.stringify({revision:data.revision,updates:Object.entries(snapshot).map(([record_id,a])=>({record_id,...a}))})});const result=await response.json();if(!response.ok)throw Error(result.error||'保存失败');data.annotations=result.annotations;data.revision=result.revision;for(const id of Object.keys(snapshot)){if(JSON.stringify(snapshot[id])===JSON.stringify(drafts[id]))delete drafts[id];}error('');return true;}catch(e){error('保存失败：'+e.message);return false;}finally{saving=false;updateProgress();}}
async function choose(id){if(!await save())return;queue();current=filtered.find(c=>c.case_id===id)||filtered[0];render();window.scrollTo(0,0);}
$('content').addEventListener('input',e=>changeReview(e.target));
$('content').addEventListener('click',async e=>{const image=e.target.closest('[data-image]');if(image){$('largeImage').src=image.dataset.image;$('imageDialog').showModal();return;}const button=e.target.closest('button');if(button?.id==='prev'||button?.id==='next'){const i=filtered.findIndex(c=>c.case_id===current.case_id);await choose(filtered[i+(button.id==='next'?1:-1)]?.case_id);}});
$('queue').onclick=e=>{const b=e.target.closest('[data-case]');if(b)choose(b.dataset.case);};
for(const id of ['student','move','pending'])$(id).addEventListener('change',async()=>{if(!await save())return;queue();current=filtered.find(c=>c.case_id===current?.case_id)||filtered[0];render();});
$('save').onclick=async()=>{if(await save())render();};
$('export').onclick=async()=>{if(!await save())return;const r=await fetch('/api/export');if(!r.ok){error('导出失败');return;}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='f_group_review.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('closeImage').onclick=()=>$('imageDialog').close();
window.addEventListener('beforeunload',e=>{if(Object.keys(drafts).length){e.preventDefault();e.returnValue='';}});
async function load(){const r=await fetch('/api/data');if(!r.ok)throw Error(await r.text());data=await r.json();for(const sid of [...new Set(data.cases.map(c=>c.student_id))])$('student').add(new Option(sid,sid));for(const mid of [...new Set(data.cases.map(c=>c.move_id))])$('move').add(new Option(data.cases.find(c=>c.move_id===mid).move_name,mid));current=data.cases[0];render();}
load().catch(e=>{error('加载失败：'+e.message);$('content').innerHTML='';});
